// Generated by CoffeeScript 1.7.1
(function() {
  var container, exports;

  container = require("./container");

  exports = module.exports = function() {
    if (!container.settings) {
      container.initContainer();
    }
    return container;
  };

}).call(this);

//# sourceMappingURL=lazyTask.map
