// Generated by CoffeeScript 1.7.1
(function() {
  var crypto, _is;

  crypto = require("crypto");

  _is = exports.is = function(type, obj) {
    var clas;
    clas = Object.prototype.toString.call(obj).slice(8, -1);
    return obj !== void 0 && obj !== null && clas === type;
  };

  exports.getHash = function(data) {
    if (_is("Object", data)) {
      data = JSON.stringify(data);
    }
    return crypto.createHash("md5").update(data).digest("hex");
  };

}).call(this);

//# sourceMappingURL=utils.map
